### ISSUE TITLE
Place tower on top of tower that already excists

### ISSUE THREAD

**Issue by PrebenAas** [olehermanse/towers#2]
It's possible to place a tower on top of a tower that already excists. The price is also charged/withdrawn from the bank. 

In the following print screen I have three towers on top of each other, check level and total sum.

![image](https://user-images.githubusercontent.com/20104610/101336067-4a617a80-387a-11eb-9d1e-1df277b2497f.png)

**Comment by olehermanse** [comment]
This was introduced when I enabled replacing any tower, regardless of price. The logic should not allow replacing with the same tower. Fixed.
